---
title: "Avito Challenge - Piecing the Training and Test Data Together"
output:
  html_document:
    toc: true
    toc_depth: 3
    df_print: paged
    code_folding: hide
---

## 1. Introduction


## 2. Prerequisites

### 2.1 Load libraries

```{R}
# viz
library(ggplot2)
library(ggthemes)
library(grid)

# data manipulation
library(dplyr)
library(reshape2)

# Data Loading
library(readr)
```

### 2.2 Load datasets

```{R}
train = read_csv("../data/train/train.csv",locale = locale(encoding = stringi::stri_enc_get()))
test = read_csv("../data/test/test.csv",locale = locale(encoding = stringi::stri_enc_get()))
```

### 2.3 Helper functions

```{R}
# Define multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

## 3. Timeframes of each dataset

Avito serves many thousands of ads on any given day. Thus, the dataset in this competition was created by providing only a subset of the ads served during a small time periods. 

It will be important to keep in mind the temporal relationship between the training and test datasets. 

```{R}
bind_rows(
      train %>% 
            count(activation_date) %>%
            mutate(dataset = "train"), 
      test %>%
            count(activation_date) %>%
            mutate(dataset = "test")
) %>%
      ggplot(aes(x = activation_date, y = n, color = dataset)) + 
      geom_point() + geom_line() + 
      ggtitle("Number of datapoints in each dataset over time") + 
      ylab("Number of datapoints") + 
      theme_fivethirtyeight()
      

```

The training data consists of datapoints from a two week period between March 14 and March 29. There are datapoints from the first couple days in April, but very few - perhaps this was a mistake in the creation of the dataset. 

The test data consists of points primarily from April 12 to April 18 - over a week after the end of the training data. There is no overlap between the training and test datasets, in terms of their temporal setting. 

The training data consists of data from 2 weeks, and the test data consists of one week. Thus, we can potentially observe weekly periodicity/trends in the data, but we cannot hope to observe monthly/yearly trends given our dataset. 

## 4. Appearence of users

```{R}
all.data = union(
      mutate(train, dataset = "train")%>%
            select(-deal_probability), 
      mutate(test,  dataset = "test")
)
```

```{R}
tmp = all.data %>%
      group_by(user_id, dataset) %>%
      summarize(num.appearences = n()) %>%
      group_by(user_id) %>%
      mutate(total.appearences = sum(num.appearences))

```
```{R}
tmp2 = tmp %>%
      select(-total.appearences) %>%
      dcast(user_id ~ dataset)

tmp2[is.na(tmp2)] <- 0
```

```{R}
p1 = tmp2 %>%
      ggplot(aes(x = train, y = test)) + 
      geom_point(alpha = .03) + 
      geom_smooth() + 
      ggtitle("User appearences: train vs. test sets") + 
      xlab("Train appearences") + 
      ylab("Test appearences")
```
```{R}
p2 = tmp2 %>%
      select(-user_id) %>%
      cor()  %>%
      melt() %>%
      ggplot(aes(x = Var1, y = Var2, fill = value, label = value)) + 
      geom_tile() + 
      geom_text() +
      scale_fill_distiller(palette = "Spectral", limits = c(-1,1)) + 
      xlab("") + ylab("") + 
      ggtitle("Correlation - user test/train appearences")
```

```{R}
multiplot(p1, p2, ncol = 2)
```

Indeed, the same users appear in the train and test datasets. 

This will be helpful in creating "leaky" features for a regression algorithm. For example, given a test set example (which contains features such as `user_id`, and `category_name`) we can create features such as the average deal probability that a user yielded in the _training_ dataset on items of a given category. This way, we can transfer some of the information in the training set to the test set come prediction time. 











