---
title: "What's in that table? `train.csv`"
output:
  html_document:
    messages: no
    toc: true
    toc_depth: 5
    df_print: paged
    fig_height: 7
    fig_width: 11
    code_folding: hide
---

## 0. Prerequesites

### 0.0 Libraries

```{R}
# data manipulations
library(dplyr)
library(readr)
library(reshape2)
library(tidyr)

# string processing
library(stringr)

# mapping functions
library(purrr)

# viz
library(ggplot2)
library(corrplot)
library(grid)
library(ggridges)
library(GGally)


```


### 0.1 Helper functions

```{R}
# Define multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

## 1. First glance

Here, I'll load the table, and take a first glance at the columns it contains. 

Loading the data:

```{R}
# load the table
train <- read_csv("../data/application_train.csv")
```

And taking a look a the column structure:

```{R}
# get
str(train)
```

This table has 307511 observations of 122 features, of a wide variety. Many of the feature names are self explanitory and intuitively informative of a creditor's solvency (for example, `FLAG_OWN_CAR` is a binary feature which determines if the client owns a car). For other features, however, the meaning of the feature is unclear from the name, or the relevence to a creditor's solvency may not be obvious (e.g. `EXT_SOURCE_1`, `APARTMENTS_AVG`, `FLAG_DOCUMENT_2`.)

## 2. Feature distributions and meanings

The next order of business is to comb through each of the features in this table, and get a rough picture of their distributions. For the features whose meaning are not obvious from their names, I'll also try and get a better idea of what they encode. 

This is a tedious process, and only a rough exploration of the features. In later sections I'll deeper into how these features relate, and in future notebooks I'll look into how the features in this table relate to the features of other tables. 


### 2.1 `TARGET`

The target column is a binary variable - presumably indicating whether or not the client defaulted on his/her loan. 

```{R}
train %>%
      count(TARGET) %>%
      rename(count = n) %>%
      mutate(proportion = count/sum(count)) %>%
      mutate(proportion = round(proportion,2)) %>%
      ggplot(aes(x = TARGET, y = count, fill = TARGET, label = proportion)) + 
      geom_col(show.legend = F) + 
      coord_flip() + 
      geom_text()
```

Around 8% of the responses are `1`, and the remaining 92% are `0`. 

From this it's not clear if a positive of `TARGET` means that the client defaulted or not. We can look at the correlation between the target each of the numeric features to see if any features which are obviously related to increased/decreased risk of default are correlated to the target. 

```{R}
p1 <- train %>%
      select_if(is.numeric) %>%
      select(-SK_ID_CURR) %>%
      cor(use = "pairwise.complete.obs") %>%
      melt() %>%
      filter(Var2 == "TARGET" & Var1 != "TARGET") %>%
      rename(correlation = value, Variable = Var1) %>%
      mutate(positive = ifelse(correlation > 0, TRUE, FALSE)) %>%
      ggplot(aes(x = reorder(Variable, -correlation), y = correlation, fill = positive)) + 
      geom_col(show.legend = FALSE) + 
      coord_flip() + 
      ggtitle("Correlation between variables and TARGET")

p1
```

Here we can see that features usually associated with solvency like `DAYS_EMPLOYED` and `AMT_GOODS_PRICE` are negatively correlated with the target. This makes me believe that `TARGET = 1` means that the client defaulted on a loan, while `TARGET = 0` means that he did not. 

This means that only 8% of the clients defaulted on their loans. This class imbalance will surely be a challenge in building a good classifier, and will be something we will have to consider carefully in the future. 

### 2.2 `NAME_CONTRACT_TYPE`

```{R}
train %>%
      count(NAME_CONTRACT_TYPE, sort = T) %>%
      rename(count = n) %>%
      mutate(proportion = count/sum(count))
```

There are only two types of loans in the training set - cash loans (which account for 90% of the training data) and revolving loans (the remaining 10%). 

Revolving loans are arrangements in which the agreed loan amount can be withdrawn, repaid and redrawn again in number of times <a href="http://www.businessdictionary.com/definition/revolving-loan.html">(cite)</a>, while a cash loan presumably means that the loan amount is given up front, and the client is expected to repay it in full at the end of the loan period. 

Revoling loans are therefore much more flexible. it's safe to assume that Home Credit is more discerning when deciding who is eligible for these types of loans 

```{R}
train %>%
      group_by(NAME_CONTRACT_TYPE) %>%
      summarize(proportion.default = mean(TARGET)) 
```

Indeed, applicants who recieve Revolving Loans have a lower default rate than those who get cash loans. 

One can ask - which type of applicant is more likely to recieve a Revolving loan, and which is more likely to recieve a Cash loan? If indeed Home Credit only gives Revolving loans to the most trustworthy-looking clients, however, this question is probably intimately related to the client's ability to repay the loan.

In fact, it may be the case that if a client recieves a Revolving loan, its because the models Home Credit developed predicts that the client is likely to repay their loan. Thus, using this feature may be a way of transfering the insight of Home Credit's models into our own models. 

---

Looking at how the various numeric features correlate with the target variable and with an applicant's likelyhood of getting a Revolving loan, we see some interesting similarities and differences (see graph below). 

For example, high values of `AMT_CREDIT` and `AMT_ANNUITY` is negatively correlated with both `TARGET` and the likelyhood of getting a revolving loan, although the correlation is much stronger for the latter. However, having a positive value for the feature `FLAG_DOCUMENT_3` is much more negatively correlated with the likelyhood of getting a revolving loan than with the target feature (in fact, `FLAG_DOCUMENT_3` is positively correlated with`TARGET`); perhaps the presense/absense of this document is directly liked to a client's eligiblity to get a revolving loan. 



```{R, fig.height = 14}
p2 <- train %>%
      mutate(revolving = ifelse(NAME_CONTRACT_TYPE == "Revolving loans", 1, 0)) %>%
      select_if(is.numeric) %>%
      select(-SK_ID_CURR) %>%
      cor(use = "pairwise.complete.obs") %>%
      melt() %>%
      filter(Var2 == "revolving" & Var1 != "revolving") %>%
      rename(correlation = value, Variable = Var1) %>%
      mutate(positive = ifelse(correlation > 0, TRUE, FALSE)) %>%
      ggplot(aes(x = reorder(Variable, -correlation), y = correlation, fill = positive)) + 
      geom_col(show.legend = FALSE) + 
      coord_flip() + 
      ggtitle("Correlation between variables and REVOVLING")

multiplot(p1,p2)
```


It's interesting how `AMT_ANNUITY` is so negativley correlated with recieving a revolving loan. Perhaps if a client has a large annuity contract with an insurance company, they are believed to be less liquid, and therefore less likely to repay a revolving loan? Any ideas? I'll have to look into this some more.

### 2.3 `CODE_GENDER`

```{R}
train %>%
      group_by(CODE_GENDER) %>%
      summarize(count = n(),
                mean.target = mean(TARGET)) %>%
      ungroup() %>%
      mutate(proportion = round(count/sum(count),3))

```

65% of applicants are female. Almost all of the remaining applicants are male - except for for applicants which selected some sort of "other" category. 

Interestingly, on a global level, it 10% of males default on their loans, while 7% of females default on theirs. I find this type of disparity - which may seem easy to understand on the surface - very intersting to investigate further. Therefore, I'm going to to go on a bit of a tangent, and try to identify what is different between male and female candidates, in hopes of identifying why males seem more likely to default than women.

---

#### 2.3.0 Loan type

There doesn't seem to be a difference in one's likelyhood to recieve a cash or revolving loan based on gender, and so this doesn't explain the diference in the gender's solvencies. 


```{R}
train %>%
      group_by(CODE_GENDER, NAME_CONTRACT_TYPE) %>%
      count() %>%
      group_by(CODE_GENDER) %>%
      mutate(proportion = n/sum(n)) %>%
      ungroup() %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = NAME_CONTRACT_TYPE, y = proportion, fill = CODE_GENDER)) + 
      geom_col(position = "dodge") +
      ggtitle("Likelyhood of Males/Females rcieving Cash/Revolving loans")
```


#### 2.3.1 Income inequality

```{R}
train %>%
      ggplot(aes(x = AMT_INCOME_TOTAL)) + 
      geom_density() + 
      scale_x_log10() +
      ggtitle("Income Density (log-scale)")
```

Income is generally very positively skewed - hence the log scale used above. With the exception of a few very rich applicants, most applicants earn less than $1,000,000 in total income. 

Focusing on just these clients and spitting the income density, we see evidence of gender inequality in total income (see graph below). 



```{R}
p3 = train %>%
      filter(CODE_GENDER != "XNA") %>%
      filter(AMT_INCOME_TOTAL <= 1e6) %>%
      ggplot(aes(x = AMT_INCOME_TOTAL, fill = CODE_GENDER))  + 
      geom_density(alpha = .6, show.legend = F) + 
      scale_x_log10() +
      ggtitle("Income Density (log-scale)")

p4 = train %>%
      filter(CODE_GENDER != "XNA") %>%
      filter(AMT_INCOME_TOTAL <= 1e6) %>%
      ggplot(aes(x = AMT_INCOME_TOTAL, fill = CODE_GENDER))  + 
      geom_density(alpha = .6, position = "fill") + 
      scale_x_log10() +
      ggtitle("Income Proportion (log-scale)") + 
      geom_vline(xintercept = 150000, linetype = "dashed", color = "red")

multiplot(p3, p4, cols = 2)
```

Men's salaries are shifted towards higher salaries, and the densities of men's and women's salaries have a similar shape. Men are more likely to recieve very high salaries: although men account for only 35% of the applicants in the training set, they hold 42% of positions that pay greater than \$150,000, 49% of positions that pay greater than \$250,000, and 55% of positions that pay greater than \$500,000. 

This may be evidence that high paying leadership positions are generaly reserved for men - which is consistent with our knowledge of present inequalities in the workplace. 

Although this phenomenon is interesting, it does not explain on its own why men seem to default on their loans more f frequently. 

#### 2.3.2 More inequality? `AMT_GOODS_PRICE`, `AMT_CREDIT` and `AMT_ANNUITY`

The distributions of the features `AMT_GOODS_PRICE`, `AMT_CREDIT` and `AMT_ANNUITY` are also positively skewed, and fairly mound shaped on the log-scale:

```{R}
p5 = train %>%
      ggplot(aes(x = AMT_GOODS_PRICE)) + 
      geom_density() +
      scale_x_log10()  +
      geom_vline(xintercept = 2.6e6, linetype = "dashed", color = "red") + 
      ggtitle("Goods Price (log-scale)")

p6 = train %>%
      ggplot(aes(x = AMT_CREDIT)) + 
      geom_density()  +
      scale_x_log10() +
      geom_vline(xintercept = 3e6, linetype = "dashed", color = "red") + 
      ggtitle("Credit amount (log-scale)")

p7 = train %>%
      ggplot(aes(x = AMT_ANNUITY)) + 
      geom_density()  +
      scale_x_log10() +
      geom_vline(xintercept = 1.3e5, linetype = "dashed", color = "red") +
      geom_vline(xintercept = 3.5e3, linetype = "dashed", color = "red") +
      ggtitle("Annuity amount (log-scale)")
      
multiplot(p5,p6,p7, cols = 1)
```



Keeping only those records within the red bands in the graphs above goods, and again splitting by gender, we see little evidence of gender inequality in the Goods prices and Credit amounts (first and second rows of graph below).

When we look at the annuity amount, however, we see a similar phenomenon as the one observed in total income, split by gender; the shape of the annuity amounts - split by gender - are roughly the same, but the male annuities are slightly shifted towards higher values (third row in graph below). 

```{R}
p8 = train %>%
      filter(AMT_GOODS_PRICE <= 2.6e6) %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = AMT_GOODS_PRICE, fill = CODE_GENDER))  + 
      geom_density(alpha = .6, show.legend = F) + 
      scale_x_log10() +
      ggtitle("Goods Price Density (log-scale)")

p9 = train %>%
      filter(AMT_GOODS_PRICE <= 2.6e6) %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = AMT_GOODS_PRICE, fill = CODE_GENDER))  + 
      geom_density(alpha = .6, position = "fill", show.legend = FALSE) + 
      scale_x_log10() +
      ggtitle("Goods Price Proportion (log-scale)") 

p10 = train %>%
      filter(AMT_CREDIT <= 3e6) %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = AMT_CREDIT, fill = CODE_GENDER))  + 
      geom_density(alpha = .6, show.legend = F) + 
      scale_x_log10() +
      ggtitle("Credit Density (log-scale)")

p11 = train %>%
      filter(AMT_CREDIT <= 3e6) %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = AMT_CREDIT, fill = CODE_GENDER))  + 
      geom_density(alpha = .6, position = "fill", show.legend = FALSE) + 
      scale_x_log10() +
      ggtitle("Credit Proportion (log-scale)")

p12 = train %>%
      filter(between(AMT_ANNUITY, 3.5e3, 1.3e5)) %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = AMT_ANNUITY, fill = CODE_GENDER))  + 
      geom_density(alpha = .6, show.legend = F) + 
      scale_x_log10() +
      ggtitle("Annuity amount Density (log-scale)")

p13 = train %>%
      filter(between(AMT_ANNUITY, 3.5e3, 1.3e5)) %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = AMT_ANNUITY, fill = CODE_GENDER))  + 
      geom_density(alpha = .6, position = "fill", show.legend = FALSE) + 
      scale_x_log10() +
      ggtitle("Annuity amount Proportion (log-scale)")

multiplot(p8, p9, p10, p11, p12, p13,layout = matrix(c(1,2,3,4,5,6), ncol = 2,byrow = TRUE))
```

Again - although interesting - the pattern of higher annuity for men than women does not increase the apparent pattern of lower solvency of men than women. In fact - the overall correlation between annuity ammount and likelihood to default is negative (although close to zero in absolute value). 

---

We see some interesting inequalities between men and women with regard to Income, Credit, Annuity, and Goods. Perhaps the interactions distributions of these two features - and how they affect likelihood to default differently for men and women - may give us insight into why men default on their loans more often. 

Below are six plots, one for each of the pairs features in {`AMT_INCOME_TOTAL`, `AMT_GOODS_PRICE`, `AMT_CREDIT`, `AMT_ANNUITY`}. The first row of each plot shows a 2D density plot of the pair of features, split by gender. The heat maps (tile charts) in the second rows of each figure are more involved: they are created using the following procedure:

- Split each (log) feature into 20 equally sized bins. 
- Compute the number of records that fall into each pair of bins, for the two features. This will correspond with the opacity of the final tiles. 
- Compute the average default rate within the bins. This will correspond with the color of the tiles. 
- Split the heatmap by gender. 


I'm hoping to see one of two interesting things in these visualizations: first, it would be intersting to observe differences in the 2D distributions of the features for men and women. Even better yet - I'm looking to see if these differences in distributions also correspond to areas of very different default rates - for example, if women tend to have low income but high annuity more frequently than men, and this charactaristic is also associated with low default rates (not sure if this is true yet...) 

```{R}
# number of bins to split continuous variables into
bins = 20
```
```{R}
tmp = train %>%
      select(AMT_INCOME_TOTAL, AMT_CREDIT, AMT_GOODS_PRICE, AMT_ANNUITY, CODE_GENDER, TARGET)  %>%
      mutate(income.log = log(AMT_INCOME_TOTAL), 
             credit.log = log(AMT_CREDIT), 
             goods.log = log(AMT_GOODS_PRICE), 
             annuity.log = log(AMT_ANNUITY)) %>%
      mutate(income.bin = cut(income.log, bins), 
             credit.bin = cut(credit.log, bins),
             goods.bin = cut(goods.log, bins), 
             annuity.bin = cut(annuity.log, bins))
             
```

###### Income vs Credit

```{R}
p14 <- tmp %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = income.log, y = credit.log)) + 
      stat_density_2d(aes(fill = ..level..), geom = "polygon", show.legend = FALSE) + 
      facet_wrap(~CODE_GENDER) +
      ggtitle("Densities over Income and Credit")


p15 <- tmp %>%
      group_by(income.bin, credit.bin, CODE_GENDER) %>%
      filter(CODE_GENDER != "XNA") %>%
      summarize(target.mean = mean(TARGET), 
                count = n()) %>%
      ungroup() %>%
      group_by(CODE_GENDER) %>%
      mutate(proportion = count/sum(count)) %>%
      ungroup() %>%
      filter(count > 1) %>%
      ggplot(aes(x = income.bin, y = credit.bin, fill = target.mean, alpha = proportion)) + 
      geom_tile() + 
      scale_fill_distiller(palette = "Spectral") + 
      scale_alpha(range = c(0.2, 1)) + 
      ggtitle("Income and Credit bins, versus target") + 
      facet_wrap(~CODE_GENDER) + 
      theme(axis.text.x = element_text(angle = 45, hjust = 1))

multiplot(p14, p15, cols = 1)
```


Again, we can see that men tend to have higher income and slightly higher credit than women. In terms of the higher default rate, I don't see a clear indication that high credit and high income leads to high default rate - it looks like men have higher default rates evenly across the distributions of income and credit. 

###### Income vs Annuity


```{R}
p16 <- tmp %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = income.log, y = annuity.log)) + 
      stat_density_2d(aes(fill = ..level..), geom = "polygon", show.legend = FALSE) + 
      facet_wrap(~CODE_GENDER) +
      ggtitle("Densities over Income and Annuity")


p17 <- tmp %>%
      group_by(income.bin, annuity.bin, CODE_GENDER) %>%
      filter(CODE_GENDER != "XNA") %>%
      summarize(target.mean = mean(TARGET), 
                count = n()) %>%
      ungroup() %>%
      group_by(CODE_GENDER) %>%
      mutate(proportion = count/sum(count)) %>%
      ungroup() %>%
      filter(count > 1) %>%
      ggplot(aes(x = income.bin, y = annuity.bin, fill = target.mean, alpha = proportion)) + 
      geom_tile() + 
      scale_fill_distiller(palette = "Spectral") + 
      scale_alpha(range = c(0.2, 1)) + 
      ggtitle("Income and Annuity bins, versus target") + 
      facet_wrap(~CODE_GENDER) + 
      theme(axis.text.x = element_text(angle = 45, hjust = 1))

multiplot(p16, p17, cols = 1)

```


Again, we can see that men clearly tend to have higher annuity and income; the "hot" spots in the density plot in the first row tend to be shifted up and right for men compared to women. The higher density in this corner, however, does not seem to correspond with pockets of higher default rates. 


###### Income vs Goods


```{R}
p18 <- tmp %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = income.log, y = goods.log)) + 
      stat_density_2d(aes(fill = ..level..), geom = "polygon", show.legend = FALSE) + 
      facet_wrap(~CODE_GENDER) +
      ggtitle("Densities over Income and Goods")


p19 <- tmp %>%
      group_by(income.bin, goods.bin, CODE_GENDER) %>%
      filter(CODE_GENDER != "XNA") %>%
      summarize(target.mean = mean(TARGET), 
                count = n()) %>%
      ungroup() %>%
      group_by(CODE_GENDER) %>%
      mutate(proportion = count/sum(count)) %>%
      ungroup() %>%
      filter(count > 1) %>%
      ggplot(aes(x = income.bin, y = goods.bin, fill = target.mean, alpha = proportion)) + 
      geom_tile(show.legend = F) + 
      scale_fill_distiller(palette = "Spectral") + 
      scale_alpha(range = c(0.2, 1)) + 
      ggtitle("Income and Goods bins, versus target") + 
      facet_wrap(~CODE_GENDER) + 
      theme(axis.text.x = element_text(angle = 45, hjust = 1))

multiplot(p18, p19, cols = 1)
```

Nothing particularly exciting here. 


###### Credit vs Annuity


```{R}
p20 <- tmp %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = credit.log, y = annuity.log)) + 
      stat_density_2d(aes(fill = ..level..), geom = "polygon", show.legend = FALSE) + 
      facet_wrap(~CODE_GENDER) +
      ggtitle("Densities over Credit and Annuity")


p21 <- tmp %>%
      group_by(credit.bin, annuity.bin, CODE_GENDER) %>%
      filter(CODE_GENDER != "XNA") %>%
      summarize(target.mean = mean(TARGET), 
                count = n()) %>%
      ungroup() %>%
      group_by(CODE_GENDER) %>%
      mutate(proportion = count/sum(count)) %>%
      ungroup() %>%
      filter(count > 1) %>%
      ggplot(aes(x = credit.bin, y = annuity.bin, fill = target.mean, alpha = proportion)) + 
      geom_tile() + 
      scale_fill_distiller(palette = "Spectral") + 
      scale_alpha(range = c(0.2, 1)) + 
      ggtitle("Credit and Annuity bins, versus target") + 
      facet_wrap(~CODE_GENDER) + 
      theme(axis.text.x = element_text(angle = 45, hjust = 1))

multiplot(p20, p21, cols = 1)

```

Nothing revealing about the differences in default rate relating to densities here. It is interesting that credit and annuity are so highly correlated, however. We'll look into this later. 


###### Credit vs Goods

```{R}
p22 <- tmp %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = credit.log, y = goods.log)) + 
      stat_density_2d(aes(fill = ..level..), geom = "polygon", show.legend = FALSE) + 
      facet_wrap(~CODE_GENDER) +
      ggtitle("Densities over Credit and Goods")


p23 <- tmp %>%
      group_by(credit.bin, goods.bin, CODE_GENDER) %>%
      summarize(target.mean = mean(TARGET), 
                count = n()) %>%
      ungroup() %>%
      group_by(CODE_GENDER) %>%
      mutate(proportion = count/sum(count)) %>%
      ungroup() %>%
      filter(count > 1) %>%
      ggplot(aes(x = credit.bin, y = goods.bin, fill = target.mean, alpha = proportion)) + 
      geom_tile() + 
      scale_fill_distiller(palette = "Spectral") + 
      scale_alpha(range = c(0.2, 1)) + 
      ggtitle("Credit and Goods bins, versus target") + 
      facet_wrap(~CODE_GENDER) + 
      theme(axis.text.x = element_text(angle = 45, hjust = 1))

multiplot(p22, p23, cols = 1)
```

The densities of credit and goods prices are very similar for men and women. Again, these two features are very highly correlated - more later. 


###### Annuity vs Goods


```{R}
p24 <- tmp %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = annuity.log, y = goods.log)) + 
      stat_density_2d(aes(fill = ..level..), geom = "polygon", show.legend = FALSE) + 
      facet_wrap(~CODE_GENDER) + 
      ggtitle("Densities over Annuity and Goods")


p25 <- tmp %>%
      group_by(annuity.bin, goods.bin, CODE_GENDER) %>%
      summarize(target.mean = mean(TARGET), 
                count = n()) %>%
      ungroup() %>%
      group_by(CODE_GENDER) %>%
      mutate(proportion = count/sum(count)) %>%
      ungroup() %>%
      group_by(CODE_GENDER) %>%
      mutate(proportion = count/sum(count)) %>%
      ungroup() %>%
      filter(count > 1) %>%
      ggplot(aes(x = annuity.bin, y = goods.bin, fill = target.mean, alpha = proportion)) + 
      geom_tile(show.legend = F) + 
      scale_fill_distiller(palette = "Spectral") + 
      scale_alpha(range = c(0.2, 1)) + 
      ggtitle("Annuity and Goods bins, versus target") + 
      facet_wrap(~CODE_GENDER) + 
      theme(axis.text.x = element_text(angle = 45, hjust = 1))

multiplot(p24, p25, cols = 1)
```

Here, we notice that its more common for men to have very low Goods price, but low/medium annuity. From the heatmaps, it seems like low goods prices and annuity tends to lead to higher default rates. Very few applications fall under this category, however, so this evidence is very shakey. 


--- 

Unfortunately, just looking at income, annuity, credit, and goods prices doesnt reveal what it is about men that leads to overall higher default rates. To get to the bottom of it, I'll need to dig a bit deeper into what's different between men and women in this dataset. 


#### 2.3.4 Getting to the bottom of it: occupation differences between men and women

One potential explanation for the difference between male and female solvency could be differences in occupations frequently occupied by males and females, and how occupations relate to solvency.

This idea is the topic of this subsection. In it we not only come to a potential explanation as to why men tend to default more frequently than women, but also explore features regarding the occupation of applicants such as `NAME_INCOME_TYPE` and `OCCUPATION_TYPE`.

---

Looking at the distribution of males and females in the various occupations (below), we see that the majority of applicants occupy one of the positions **Working, State Servant, Pensioner**, or **Commercial Associate** (top left). I'll refer to these occupations as the "**big four**" occupations. 

People who are either on Maternity leave or unemployed have a much higher likelyhood of defaulting on their debts (top right), though these occupations constitute a very small minority of the applicants. Of the big four occupations, the default rate hovers around 8%, though those of the occupation **working** default at a slightly higher rate, and those with the occupations **state servant** and **pensioner** default at a lower rate. 

Although 60% of all applicants of the **Working** occupation are female (bottom left), 60% of male applicants are of this occupation, while only 47% of female applicants are of this occupation (bottom right). In other words, although most "workers" are female, a larger proportion of males are workers than that of females. Since people of the **working** occupation have a slightly higher default rate, this may explain why males have a higher global default rate. <ul>*Although*</ul>, we cannot know in which direction the causation lies (is male default rate higher because most males are workers, or are worker default rates high because many workers are male???)

Along this same logic: A larger proportion of females are state servants and pensioners, compared to the proportion of males of these occupations. Since these occupations have slightly lower default rates, this could explain why females have lower default rates (same warning as before.)


```{R, fig.height = 10, figh.width = 12}
p26 <- train %>%
      filter(CODE_GENDER != "XNA") %>%
      count(NAME_INCOME_TYPE, CODE_GENDER) %>%
      rename(count = n) %>%
      ggplot(aes(x = NAME_INCOME_TYPE, y = count, fill = CODE_GENDER)) + 
      geom_col(position = "dodge") + 
      coord_flip() + 
      ggtitle("Employment type - global count")

p27 <- train %>%
      filter(CODE_GENDER != "XNA") %>%
      count(NAME_INCOME_TYPE, CODE_GENDER)  %>%
      rename(count = n) %>%
      group_by(NAME_INCOME_TYPE) %>%
      mutate(proportion = count/sum(count)) %>%
      ungroup() %>%
      mutate(label = paste(round(proportion*100,3), "%")) %>%
      ggplot(aes(x = NAME_INCOME_TYPE, y = count, fill = CODE_GENDER, label = label)) +
      geom_col(position = "fill", show.legend = F) + 
      coord_flip() + 
      geom_text(position = position_fill()) + 
      ggtitle("Employ. Type. Percentage by gender")


p28 <- train %>%
      filter(CODE_GENDER != "XNA") %>%
      count(NAME_INCOME_TYPE, CODE_GENDER)  %>%
      rename(count = n) %>%
      group_by(CODE_GENDER) %>%
      mutate(proportion = count/sum(count)) %>%
      ungroup() %>%
      mutate(proportion = round(proportion, 3)) %>%
      mutate(label = paste(proportion*100, "%")) %>%
      ggplot(aes(x = NAME_INCOME_TYPE, y = proportion, fill = CODE_GENDER, label = label)) +
      geom_col(position = "dodge", show.legend = F) + 
      coord_flip() + 
      geom_text(position = position_dodge(width = 0.9)) + 
      ggtitle("Within gender emply. type perc.")

p29 <- train %>%
      count(NAME_INCOME_TYPE, TARGET) %>% 
      mutate(TARGET = as.factor(TARGET)) %>%
      ggplot(aes(x = NAME_INCOME_TYPE, y = n, fill = TARGET)) + 
      geom_col(position = "fill") + 
      coord_flip() + 
      scale_fill_discrete( h = c(50,1000)) + 
      geom_hline(yintercept = .08, linetype = "dashed")

multiplot(p26, p29, p27, p28, layout = matrix(c(1,1,2,3,4,4), byrow = T, nrow = 2))
      
```


Beyond the income type `NAME_INCOME_TYPE`, another interesting feature is the occupation type, `OCCUPATION_TYPE`, and the differences in the occupation makeup between genders (below). 

Applicants with certain occupations tend to have a higher default rate than others (top right). Furthermore, the distribution of applicants within a certain gender might explain why men have a higher default rate than women on average. 

One of the occupations that simultaneouly has one the highest average default rate and frequency is *Laborers*, with an average default rate of around 11% (top right), and over 10% for both men and women with this occupation (bottom right). Around 31% of men have this occupation, while only 11% of women have this occupation. Similarly, around 16% of men are drivers - an occupation with a default rate of over 10% for men - and less than 5% of women are women. 

On the other hand, a larger percentage of women occupy low default rate occupations than man - 11% of women are of occupation *Core Staff* - an occupation with default rates less than 8%, while only ~6% of men are Core Staff. ~5% of women are accountants - an occupation with default rates of around 6% - while only around 1% of men are accountants. 
This disparity in the proportion of men and women who occupy different jobs, and the fact that some occupations corresond to higher default rates than others, may finally lead us to our explanation as to why men have a higher default rate than women in this dataset.

It also leads us to an additional insight - not only are the gender and occupation of an applicant important features to consider, but also their interaction. For some occupations, such as laborers, drivers and medicine staff, the average default rates are rather different for male and female applicants of that occupation. 


```{R}
# order the bars in the below bar charts by the frequency of occupations
occ_order = train %>% 
      count(OCCUPATION_TYPE) %>%
      arrange(n) %>%
      .$OCCUPATION_TYPE

p34 <- train %>%
      filter(CODE_GENDER != "XNA") %>%
      group_by(OCCUPATION_TYPE) %>%
      summarise(mean_target = mean(TARGET)) %>%
      ggplot(aes(x = OCCUPATION_TYPE, y = mean_target)) + 
      geom_col() +
      scale_x_discrete(limits=occ_order) + 
      coord_flip() + 
      ggtitle("Average default rate by occupation") + 
      geom_hline(yintercept = .08, linetype = "dashed")

p35 <- train %>%
      filter(CODE_GENDER != "XNA") %>%
      group_by(OCCUPATION_TYPE, CODE_GENDER)  %>% 
      summarise(target_mean = mean(TARGET)) %>%
      ggplot(aes(x = OCCUPATION_TYPE, y = target_mean, fill = CODE_GENDER)) + 
      geom_col(position = "dodge") + 
      coord_flip() + 
      scale_x_discrete(limits=occ_order) + 
      ggtitle("Average default rate by occupation/gender") + 
      geom_hline(yintercept = .08, linetype = "dashed")

p36 <- train %>%  
      filter(CODE_GENDER != "XNA") %>%
      count(OCCUPATION_TYPE) %>%
      ggplot(aes(x = OCCUPATION_TYPE, y = n )) + 
      geom_col() + 
      coord_flip() + 
      scale_x_discrete(limits=occ_order) + 
      ggtitle("Occupation Frequency")

p37 <- train %>%  
      filter(CODE_GENDER != "XNA") %>%
      count(OCCUPATION_TYPE, CODE_GENDER) %>%
      group_by(CODE_GENDER) %>%
      mutate(gender_proportion = n/sum(n)) %>%
      ggplot(aes(x = OCCUPATION_TYPE, y = gender_proportion , fill = CODE_GENDER)) + 
      geom_col(show.legend = F, position = "dodge") + 
      coord_flip() + 
      scale_x_discrete(limits=occ_order) + 
      ggtitle("Occupation proportion by gender")

multiplot(p36, p34,p37, p35, layout = matrix(c(1,2,3,4), nrow = 2, byrow = T))
```


```{R}
train %>%
      group_by(ORGANIZATION_TYPE) %>%
      summarize(num = n(), 
                target_mean = mean(TARGET)) %>%
      melt(id.vars = c("ORGANIZATION_TYPE")) %>%
      ggplot(aes(x = reorder(ORGANIZATION_TYPE, value, FUN = min), y = value, fill = variable)) + 
      geom_col(show.legend = F) +
      coord_flip() + 
      facet_wrap(~variable, scales = "free_x") +
      xlab("ORGANIZATION_TYPE Type") + 
      geom_hline(yintercept = .08, linetype = "dashed")

```


### 2.4 Relationship between income, goods credit and annuity

In the previous section, we looked at how people of different genders and occupations vary in terms of income `AMT_INCOME_TOTAL`, and the properties of their loan, including the loan amount `AMT_CREDIT`, the dollar value of the goods they are purchasing with the loan `AMT_GOODS_PRICE`, and the annuity price, `AMT_ANNUITY`. 

We did not, however, look into how the interactions of these loan properties affects an applicants likelihood of paying back his/her loan. This will be the topic of this subsection. 


#### 2.4.1 Ratios relevant to application

First, I'll create a series of columns of the ratios of each pair of columns in `AMT_INCOME_TOTAL`, `AMT_ANNUITY`, `AMT_GOODS_PRICE`, `AMT_CREDIT`.

```{R}
train <- train %>%
      mutate(credit_income_rat = AMT_CREDIT/AMT_INCOME_TOTAL, 
             annuity_income_rat = AMT_ANNUITY/AMT_INCOME_TOTAL, 
             goods_income_rat = AMT_GOODS_PRICE/AMT_INCOME_TOTAL, 
             goods_credit_rat = AMT_GOODS_PRICE/AMT_CREDIT, 
             annuity_credit_rat = AMT_ANNUITY/AMT_CREDIT, 
             goods_annuity_rat = AMT_GOODS_PRICE/AMT_ANNUITY)
```

At first glance, none of these ratios are strongly correlated with `TARGET`. Many of them are highly correlated with each other, but this is just because credit, goods price, and annuity are so strongly correlated to each other. 

```{R}
train %>%
      select(TARGET, credit_income_rat, annuity_income_rat, 
             goods_income_rat, goods_credit_rat, 
             annuity_credit_rat, goods_annuity_rat) %>%
      ggpairs()

```



Of the univariate distributions of these 


```{R}
p1 <- train %>%
      ggplot(aes(x = goods_credit_rat)) + 
      geom_density() + 
      geom_vline(xintercept = 1, linetype = "dashed", color = "red") + 
      ggtitle("Goods over Credit")

p2 <- train %>%
      ggplot(aes(x = goods_income_rat)) + 
      geom_density() + 
      geom_vline(xintercept = 1, linetype = "dashed", color = "red") + 
      ggtitle("Goods over Income")

p3 <- train %>%
      ggplot(aes(x = credit_income_rat)) + 
      geom_density() + 
      geom_vline(xintercept = 1, linetype = "dashed", color = "red") + 
      ggtitle("Credit over Income") 

p4 <- train %>%
      ggplot(aes(x = annuity_income_rat)) + 
      geom_density() + 
      geom_vline(xintercept = 1, linetype = "dashed", color = "red") + 
      ggtitle("Annuity over Income") 

multiplot(p1,p2,p3,p4, cols = 2)

```


```{R}
goods_income_med = train$goods_income_rat %>% median(na.rm = T)
goods_income_std = train$goods_income_rat %>% var(na.rm = T) %>% sqrt()

train %>%
      mutate(std_dist = (goods_income_rat - goods_income_med)/goods_income_std) %>%
      mutate(dist_group = round(std_dist*3/max(std_dist, na.rm = T))) %>%
      mutate(dist_group = as.factor(dist_group)) %>%
      ggplot(aes(x = goods_income_rat, fill = dist_group)) + 
      geom_histogram() + 
      geom_vline(xintercept = goods_income_med, linetype = "dashed")

```


```{R}
train %>%
      filter(goods_income_rat <= 1) %>%
      summarise(target_mean = mean(TARGET))

```




```{R}
train %>%
      ggplot(aes(x = annuity_credit_rat)) + 
      geom_density()
```


### 2.5 `DAYS_EMPLOYED`


Looking at the number of days people have worked (below), we see two weird properties. First, the number of days are often negative (perhaps to encode the number of days "until" the person started working), and that may people have worked for an unreasonable number of days (over 300,000 - or one thousand years). 



```{R}
train %>%
      ggplot(aes(x = DAYS_EMPLOYED)) +
      geom_density()
```

The first thing I'll do is create an additional feature, called `years_employed`, which will replace unusual values of `DAYS_EMPLOYED` with `NA`, and convert the values to positive values, in terms of years. I'll also add a column for the age of applicants, in terms of years, by multiplying `DAYS_BIRTH` by $\frac{-1}{365}$.

```{R}
# Add a column for the number of years since beginning employement.
train <- train %>%
      mutate(years_employed = ifelse(DAYS_EMPLOYED > 3e5, NA, DAYS_EMPLOYED*-1/365))

# Add column for age
train <- train %>% 
      mutate(years_birth = DAYS_BIRTH * -1/365)

```
```{R}
train %>%
      ggplot(aes(x = years_employed)) +
      geom_density() + 
      ggtitle("Distribution of years employed (reasonable values only)")
```

Most people have been working between 0 and 10 years, with the majority of the weight towards very little time. Some people have worked up to 50 years. 

18% of records (55374 out of 307511) contain unreasonable values or `DAYS_EMPLOYED`. These 55374 records are distributed entirely amongst those applicants with the occupation **Pensioner** and **Unemployed** (below) - presumably because it doesn't make sense to count the number of days someone is ``employed" if they are unemplyed or retired. 


```{R}
train %>%
      mutate(isna = is.na(years_employed)) %>%
      group_by(NAME_INCOME_TYPE) %>%
      summarise(num_missing = sum(isna), 
                num_records = n()) %>%
      mutate(percent_missing = num_missing/num_records)
```



---

Below we can see male applicants tend to have worked for less time than women applicants. Furthermore, male applicants tend to be much youger than women applicants. 

```{R}
p30 <- train %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = years_employed, fill = CODE_GENDER)) + 
      geom_density(alpha = .7, show.legend = F) +
      ggtitle("Densities of years worked, by gender")

p31 <- train %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = years_employed, fill = CODE_GENDER)) +
      geom_density(position = "fill")

p32 <- train %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = years_birth, fill = CODE_GENDER)) +
      geom_density(alpha = .7, show.legend = F) + 
      ggtitle("Applicant age, by gender")

p33 <- train %>%
      filter(CODE_GENDER != "XNA") %>%
      ggplot(aes(x = years_birth, fill = CODE_GENDER)) +
      geom_density( position = "fill")

multiplot(p30,p31,p32,p33, layout = matrix(c(1,2,3,4), byrow = T, ncol = 2))
```

---

Next, I'll look into the relationships between career length, age, loan charactaristics and default rate. 

Surprisingly, on a global level, age and number of years an applicant has worked uncorrelated to the probability of defaulting, as well as income, credit, annuity, and goods price. Again, we observe a weak positive correlation between income and credit, goods price, and annuity. 


```{R}
train %>%
      select(TARGET, years_employed, years_birth, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_GOODS_PRICE, AMT_ANNUITY) %>%
      cor(use = "pairwise.complete.obs") %>%
      melt() %>%
      mutate(correlation = round(value, 3)) %>%
      ggplot(aes(x = Var1, y = Var2, fill = correlation, label = correlation)) + 
      geom_tile() + 
      geom_text(size = 3) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
      scale_fill_distiller(palette = "Spectral", limits = c(-1,1))
```

When we look at this same correlation plot, split by the occupation (for the ``big four" occupations only), we see very similar correlation patterns as for the global correlation. 

There are a few features in these correlation plots which are different when we split by occupation, however, including:

- Age and years working are somewhat strongly positively correlated, _except_ for applicants of the occupation *Pensioner*. 
- Although For Pensioners, age is not especially strongly correlated with income, annuity or credit, 

```{R}

train %>% 
      select(NAME_INCOME_TYPE,TARGET, years_employed,years_birth, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_GOODS_PRICE, AMT_ANNUITY) %>%
      filter(NAME_INCOME_TYPE %in% c("Commercial associate", "Pensioner", "State servant", "Working")) %>%
      group_by(NAME_INCOME_TYPE) %>%
      nest() %>%
      mutate(corrmat =  map(.x = data, .f = function(x) cor(x, use = "pairwise.complete.obs") %>%
                                  melt())) %>%
      select(-data) %>%
      unnest() %>%
      mutate(correlation = round(value,3)) %>%
      ggplot(aes(x = Var1, y = Var2, fill = correlation, label = correlation)) + 
      geom_tile() + 
      facet_wrap(~NAME_INCOME_TYPE) + 
      scale_fill_distiller(palette = "Spectral", limits = c(-1,1)) + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
      geom_text(size= 2)
```








































